### ISSUE TITLE
modifying images UEFITool NE

### ISSUE THREAD

**Issue by OSDEVYT** [LongSoft/UEFITool#381] opened 2023-10-22 02:09 UTC
when is the ability for modifying images coming

**Comment by NikolajSchlej** [comment] 2023-10-22 18:27
Dupe of https://github.com/LongSoft/UEFITool/issues/67, but the real answer is "when I get enough time and resources to implement it, or somebody else contributes it".

**Closed as completed by NikolajSchlej** 2023-10-22 18:27 UTC
