### ISSUE TITLE
Remove

### ISSUE THREAD

**Issue by ogamespec** [LongSoft/UEFITool#188] opened 2019-12-25 15:58 UTC
Always not active (broken?)

![image](https://user-images.githubusercontent.com/5828819/71448100-86263180-2748-11ea-8ff5-1914d5c2a632.png)

**Comment by vit9696** [comment] 2019-12-25 20:43
Duplicate of https://github.com/LongSoft/UEFITool/issues/67.

**Closed by vit9696** 2019-12-25 20:43 UTC
