### ISSUE TITLE
Modifying bios

### ISSUE THREAD

**Issue by htm23x** [LongSoft/UEFITool#365] opened 2023-06-15 06:46 UTC
Hi,
first at all, many thanks for UEFI Tool. It's a very handy utility!
But just a question, please: is there any compiling option to allow the new engine to edit/modify/save/write the bios?
AFAIK only the old engine can edit/mod/write bioses, but it messes sometimes the PEI parts and the resulting bios hangs.
How can I enable edit/modify/write bioses with the new engine one?
Many thanks.

**Comment by platomav** [comment] 2023-06-15 21:48
Editing is not implemented at NE. Duplicate of https://github.com/LongSoft/UEFITool/issues/67

https://github.com/LongSoft/UEFITool/issues/364#issuecomment-1589787918

**Closed as completed** 2023-06-16 04:06 UTC
