### ISSUE TITLE
CMake: INSTALL TARGETS given no RUNTIME DESTINATION for executable target

### ISSUE THREAD

**Issue by platomav** [LongSoft/UEFITool#342] opened 2023-02-15 17:34 UTC
When attempting to build under Docker using Debian Buster as base, the following error occurs at CMake step:

``` bash
+ cd UEFIExtract
+ cmake .
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:71 (INSTALL):
  INSTALL TARGETS given no RUNTIME DESTINATION for executable target
  "UEFIExtract".
```

Here is a quick Dockerfile to reproduce the issue:

``` dockerfile
FROM python:3.11-slim-buster AS uefitool_build

WORKDIR ./

ARG UEFITOOL_GIT_URL="https://github.com/LongSoft/UEFITool.git"
ARG UEFITOOL_GIT_SHA="633561adbf49cd45bf33825ae739a8af8003d06b"

RUN set -xue \
    && apt-get update -yq \
    && apt-get install -yq --no-install-recommends \
        git \
        cmake \
        build-essential \
    && git clone "${UEFITOOL_GIT_URL}" \
    && (cd UEFITool \
    && git checkout "${UEFITOOL_GIT_SHA}" \
    && (cd UEFIExtract && cmake . && make install) \
    && (cd UEFIFind && cmake . && make install)) \
    && rm -rf UEFITool \
    && (uefiextract || [ $? -eq 1 ]) > /dev/null \
    && (uefifind || [ $? -eq 1 ]) > /dev/null

ENTRYPOINT ["uefiextract"]
```

I have also attached a small archive with the test Dockerfile, a test python script to build/run the container and the error output log.

[uefitool_test.zip](https://github.com/LongSoft/UEFITool/files/10745822/uefitool_test.zip)

**Comment by NikolajSchlej** [comment] 2023-02-15 17:41
This is caused by an outdated version of CMake, but it can be fixed by adding that part explicitly. New CMake versions have a default for that now, that's how the issue have been missed.

**Comment by NikolajSchlej** [comment] 2023-02-16 00:36
Fixed in https://github.com/LongSoft/UEFITool/commit/c4ed9c310d5a14d3ec1feb00f1f294aadcc985d2, that `Dockerfile` runs now.

**Closed as completed by NikolajSchlej** 2023-02-16 00:36 UTC
Labels: 1. Expected, Build system

**Comment by platomav** [comment] 2023-02-16 21:29
Can confirm that it works now with old cmake. Thank you for the quick fix, Nikolaj!
