### ISSUE TITLE
BIOS region parsed as Padding at NE A56

### ISSUE THREAD

**Issue by platomav** [LongSoft/UEFITool#181] opened 2019-08-24 11:31 UTC
Something at NE A56 is causing some BIOS regions to be parsed/shown as blobs of Padding:

![Capture1](https://user-images.githubusercontent.com/11527726/63636683-2117dd80-c67b-11e9-95d2-5afb2e5beadd.PNG)

![Capture2](https://user-images.githubusercontent.com/11527726/63636685-2117dd80-c67b-11e9-834d-581bf00695b5.PNG)

Sample will be sent privately due to special circumstances.

**Comment by NikolajSchlej** [comment] 2019-08-24 19:15
It's caused by #180, closing as duplicate.

**Closed by NikolajSchlej** 2019-08-24 19:15 UTC
