### ISSUE TITLE
Right click options grayed out, can't insert module 

### ISSUE THREAD

**Issue by AstroBoyMik** [LongSoft/UEFITool#179] opened 2019-08-22 08:10 UTC
I'm following a youtube guide in order to boot from nvme in my z87 board. The options below and including Rebuild are all grayed out. I can't insert the .ffs module in my .cap. Please advise.

**Comment by vit9696** [comment] 2019-08-22 09:09
The thing is still in progress due to low priority. Closing as a duplicate of #67.

**Closed by vit9696** 2019-08-22 09:09 UTC

**Comment by megapro17** [comment] 2022-10-06 22:00
low priority?? wtf? one of the main features
