### ISSUE TITLE
Uefi tool dont see me from bios like Apollo Lake chipset

### ISSUE THREAD

**Issue by remrtehno** [LongSoft/UEFITool#85] opened 2017-11-15 08:09 UTC
[E402NA-F1.306.zip](https://github.com/LongSoft/UEFITool/files/1473808/E402NA-F1.306.zip)

[back_ok_me_dry.zip](https://github.com/LongSoft/UEFITool/files/1473810/back_ok_me_dry.zip)
There are two files for ApolloLake chipsets.  The firts file doesnt look in Uefi tools Me region, cause I dont sure that the second file is work or have me region

**Comment by NikolajSchlej** [comment] 2017-12-03 17:50
Duplicate of #82

**Closed by NikolajSchlej** 2017-12-03 17:50 UTC
