### ISSUE TITLE
UEFITool mac packaging broken(?) in release A64

### ISSUE THREAD

**Issue by makigumo** [LongSoft/UEFITool#340] opened 2023-02-14 08:47 UTC
Hello!
It seems, that the packaging was changed, so that the released [UEFITool_NE_A64_universal_mac.zip](https://github.com/LongSoft/UEFITool/releases/download/A64/UEFITool_NE_A64_universal_mac.zip) no longer contains an `.app` package.

This is what the previous version looked like.
```sh
$ unzip -l UEFITool_NE_A63_mac.zip 
Archive:  UEFITool_NE_A63_mac.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  01-29-2023 23:41   UEFITool.app/
        0  01-29-2023 23:43   UEFITool.app/Contents/
        0  01-29-2023 23:52   UEFITool.app/Contents/MacOS/
 29921496  01-29-2023 23:52   UEFITool.app/Contents/MacOS/UEFITool
        0  01-29-2023 23:41   UEFITool.app/Contents/Resources/
   335649  01-29-2023 23:41   UEFITool.app/Contents/Resources/uefitool.icns
        0  01-29-2023 23:41   UEFITool.app/Contents/Resources/empty.lproj
      879  01-29-2023 23:41   UEFITool.app/Contents/Info.plist
        9  01-29-2023 23:41   UEFITool.app/Contents/PkgInfo
---------                     -------
 30258033                     9 files
```

And this is the current version.
```sh
unzip -l UEFITool_NE_A64_universal_mac.zip 
Archive:  UEFITool_NE_A64_universal_mac.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
 34652805  02-13-2023 03:46   UEFITool
   335649  02-13-2023 03:46   uefitool.icns
      879  02-13-2023 03:40   Info.plist
---------                     -------
 34989333                     3 files
```

This seems to be because of the `-j` argument in https://github.com/LongSoft/UEFITool/blob/new_engine/.github/workflows/main.yml#L45 added in commit  https://github.com/LongSoft/UEFITool/commit/24d61c437554f6960ebdb5376f89480b925ad59c. I think this was probably made in error.

Thank you for your consideration.

**Comment by NikolajSchlej** [comment] 2023-02-14 16:13
You are right, both about the bug and the root cause. Will be fixed later today.

**Comment by NikolajSchlej** [comment] 2023-02-14 16:39
Fixed in https://github.com/LongSoft/UEFITool/commit/633561adbf49cd45bf33825ae739a8af8003d06b

**Closed as completed by NikolajSchlej** 2023-02-14 16:39 UTC
