### ISSUE TITLE
Native support for UI Dark Mode

### ISSUE THREAD

**Issue by vit9696** [LongSoft/UEFITool#276] opened 2022-08-27 16:49 UTC
Apparently there is white text on white background in some places:

<img width="155" alt="Screenshot 2022-08-27 at 18 47 20" src="https://user-images.githubusercontent.com/4348897/187039976-06eb08b7-a3cd-480a-87a5-b689bb97e39b.png">
<img width="350" alt="Screenshot 2022-08-27 at 18 46 11" src="https://user-images.githubusercontent.com/4348897/187039978-89165fcc-86f0-4632-bed3-eda11178c7bd.png">

**Comment by NikolajSchlej** [comment] 2022-09-10 06:08
Can be resolved by switching to Qt 6.x for GH-made releases, with a 5.6.3 builds to remain supported.

**Comment by NikolajSchlej** [comment] 2022-09-10 06:09
I've tested on Qt 6.3.1, looks fine enough, but requires some minor changes to make protected range marking less glaring in dark mode.

**Comment by NikolajSchlej** [comment] 2022-09-10 06:36
<img width="1071" alt="DM_Qt6" src="https://user-images.githubusercontent.com/1845688/189472305-d3b6f302-ec7f-462c-b72b-fedfd53ef9c5.png">

**Comment by yeggor** [comment] 2022-09-10 17:13
I just now noticed that this has already been discussed. Do you think this solves the problem with protected ranges colors: https://github.com/LongSoft/UEFITool/pull/293?

**Comment by NikolajSchlej** [comment] 2022-09-13 08:33
Support for macOS dark mode had been recently added to Qt6, but had not been backported to Qt5 in any way, so we should start using Qt6 (but remain compatible with the last Qt build under LGPLv2.1 - 5.6.3, with some minor UI issues if needed) and get that for free.
- [x] add static Qt 6.4.2 x64 UEFITool build for Windows
- [x] switch to static Qt 6.4.2 universal build for macOS

@yeggor also showed that darkX colors are much nicer-looking in dark mode in #293, but I'd like to detect both Aqua and Dark modes, and switching between them dynamically.
- [x] detect the current mode dynamically, adjust BootGuard marking colors to suit the current mode (Windows)
- [x] detect the current mode dynamically, adjust BootGuard marking colors to suit the current mode (macOS)

**Comment by NikolajSchlej** [comment] 2023-02-08 06:13
Looks like we've also lost Windows XP support even for 5.6.3-based builds, this needs to be fixed by generating a separate win32 executable with 'vc141_xp' target (CMake doesn't support Qt 5 for real, so that needs to be done by pre-generated make files)
- [ ] Make sure Windows XP remains supported after all the changes, because people still run the tool there after all this years

**Comment by NikolajSchlej** [comment] 2023-02-11 01:26
Update: Qt 6.4.2 as of today does not support dark mode for its default style.

**Comment by NikolajSchlej** [comment] 2023-02-11 01:30
[Detection of dark modes enabled on macOS and Windows](https://successfulsoftware.net/2021/03/31/how-to-add-a-dark-theme-to-your-qt-application/).

**Comment by NikolajSchlej** [comment] 2023-02-12 00:09
The new win64 build of UEFITool uses Qt 6.4.2 that supports experimental dark mode by switching to classic widgets with a darker palette. The application does not start in this mode by default, but can be forced into it by adding `-platform windows:darkmode=2` commandline parameter to UEFITool.exe invocation. 

Looks like this:
![1](https://user-images.githubusercontent.com/1845688/218286380-0db19316-8174-468c-8f3c-bb3de57a5acb.png)

**Comment by NikolajSchlej** [comment] 2023-02-12 05:08
Got Windows 10+ dark mode working as expected, no overrides required:
![1](https://user-images.githubusercontent.com/1845688/218294069-61a44ac8-af68-4305-a070-5b70e747f0fe.png)

**Comment by NikolajSchlej** [comment] 2023-02-12 05:44
Now detection of dark mode and setting colors also works in macOS:
<img width="842" alt="Screenshot 2023-02-11 at 21 39 54" src="https://user-images.githubusercontent.com/1845688/218295127-360334e8-fba3-4524-a772-87cc2d8e00c0.png">

**Comment by NikolajSchlej** [comment] 2023-02-12 18:53
Done, the current CI/CD pipeline can successfully generate Qt-6.4.2-based builds for both macOS and Windows, and uses a native installed Qt5/6 on Linux. I consider this issue to be resolved, please open another one if UI Dark Mode doesn't work for you in some way.

**Closed as completed by NikolajSchlej** 2023-02-12 18:53 UTC
Labels: UI, 1. Expected

**Comment by NikolajSchlej** [comment] 2023-02-12 23:07
Confirmed macOS way to determine UI dark mode to work in Linux, enabled it there.
![1](https://user-images.githubusercontent.com/1845688/218342777-0af1c4c8-1338-4e62-bbab-2940c57e734b.png)
