### ISSUE TITLE
The Replacer don't work

### ISSUE THREAD

**Issue by yonisoft** [LongSoft/UEFITool#397] opened 2024-06-21 18:34 UTC
![image](https://github.com/LongSoft/UEFITool/assets/51174770/31ee45e0-38e2-4a64-9bec-6abac37ad632)

**Comment by NikolajSchlej** [comment] 2024-06-22 22:52
Duplicate of https://github.com/LongSoft/UEFITool/issues/67

**Closed as completed by NikolajSchlej** 2024-06-22 22:52 UTC
