### ISSUE TITLE
Unable to boot after applying UEFI Patch

### ISSUE THREAD

**Issue by lightingghost** [LongSoft/UEFITool#207] opened 2020-04-25 23:39 UTC
I am trying to disable CFG Lock with UEFI Tool and UEFI Patch. The first thing I tried is to change the bit using modified grub shell. I found that the CFG Lock is at 0x4A8

```
Form: View/Configure CPU Lock Options, FormId: 0x272D {01 86 2D 27 43 02}
0x3B24D 		One Of: CFG Lock, VarStoreInfo (VarOffset/VarName): 0x4A8, VarStore: 0x1, QuestionId: 0x14B, Size: 1, Min: 0x0, Max 0x1, Step: 0x0 {05 91 E5 03 E6 03 4B 01 01 00 A8 04 10 10 00 01 00}
0x3B25E 			One Of Option: Disabled, Value (8 bit): 0x0 {09 07 04 00 00 00 00}
0x3B265 			One Of Option: Enabled, Value (8 bit): 0x1 (default) {09 07 03 00 30 00 01}
0x3B26C 		End One Of {29 02}
0x3B26E 		One Of: Overclocking Lock, VarStoreInfo (VarOffset/VarName): 0x557, VarStore: 0x1, QuestionId: 0x14C, Size: 1, Min: 0x0, Max 0x1, Step: 0x0 {05 91 E1 03 E2 03 4C 01 01 00 57 05 10 10 00 01 00}
0x3B27F 			One Of Option: Disabled, Value (8 bit): 0x0 (default) {09 07 04 00 30 00 00}
0x3B286 			One Of Option: Enabled, Value (8 bit): 0x1 {09 07 03 00 00 00 01}
0x3B28D 		End One Of {29 02}
0x3B28F 	End Form {29 02}
```

So I run 
```setup_var_3 0x4A8 0x00``` 
to set it to be disabled. (setup_var gives an error therefore I used setup_var_3)

Also I checked with `setup_var_3 0x4A8` to make sure the bit is set. But checking with RWeverything still shows MSR locked (15th bit is 1).

Then I tried UEFIPatch, the output is 

```
PS C:\Users\light\Downloads\UEFIPatch_0.28.0_win32> .\UEFIPatch.exe .\C422WSI1.10 -o patched
parseFile: non-empty pad-file contents will be destroyed after volume modifications
patch: replaced 8 bytes at offset 41C9h 81E10080000033C1 -> 9090909090909090
patch: replaced 7 bytes at offset 27ACh 742CB9E2000000 -> 752CB9E2000000
patch: replaced 8 bytes at offset 150Fh BE0080000023CE0B -> BE0000000023CE0B
patch: replaced 10 bytes at offset 277Fh 488944245072130FBAE8 -> 488944245072130FBAE0
rebase: can't determine if TE image base is adjusted or not, rebased TE image may stop working
rebase: can't determine if TE image base is adjusted or not, rebased TE image may stop working
rebase: can't determine if TE image base is adjusted or not, rebased TE image may stop working
rebase: can't determine if TE image base is adjusted or not, rebased TE image may stop working
rebase: can't determine if TE image base is adjusted or not, rebased TE image may stop working
rebase: can't determine if TE image base is adjusted or not, rebased TE image may stop working
rebase: can't determine if TE image base is adjusted or not, rebased TE image may stop working
rebase: can't determine if TE image base is adjusted or not, rebased TE image may stop working
rebase: can't determine if TE image base is adjusted or not, rebased TE image may stop working
rebase: can't determine if TE image base is adjusted or not, rebased TE image may stop working
rebase: can't determine if TE image base is adjusted or not, rebased TE image may stop working
rebase: can't determine if TE image base is adjusted or not, rebased TE image may stop working
Image patched
```

But I cannot boot with the patched bios. 

motherboard: Asrock Rack C422 WSI/IMPI
bios: [here](https://drive.google.com/file/d/1Y5sEGMe89XUriHWHhoFG1cjezxFjMAEh/view?usp=sharing)

Any help will be appreciated.

**Comment by NikolajSchlej** [comment] 2020-11-23 05:26
Duplicate of #192.

**Closed by NikolajSchlej** 2020-11-23 05:26 UTC
